package org.openjfx.model;

public class Test {

    private int testID;
    private String name;
    private int points;
    private boolean isScored;
    private int year;
    private int session;

    //Constructors
    public Test(){}
    /**
     * Constructor
     * @param tID
     * @param name
     * @param p
     * @param isScore
     * @param y
     * @param s
     */
    public Test(int tID, String name, int p, boolean isScore, int y, int s){

        testID = tID;
        this.name = name;
        points = p;
        isScored = isScore;
        year = y;
        session = s;

    }

    /**
     * Initial Test Constructor: There is no testID field as it has yet to be generated by the db.
     * @param name
     * @param p
     * @param isScore
     * @param y
     * @param s
     */
    public Test(String name, int p, boolean isScore, int y, int s){

        this(0, name, p, isScore, y, s);

    }

    /**
     * Copy Constructor
     * @param tmp
     */
    public Test(Test tmp){

        this.testID = tmp.testID;
        this.name = tmp.name;
        this.points = tmp.points;
        this.isScored = tmp.isScored;
        this.year = tmp.year;
        this.session = tmp.session;

    }

    @Override
    public String toString(){

        return name;

    }

    //Getters
    public int getTestID() { return testID; }

    public String getName() { return name; }

    public int getPoints() { return points; }

    public boolean isScored() { return isScored; }

    public int getYear() { return year; }

    public int getSession() { return session; }

    //Setters
    public void setTestID(int testID) { this.testID = testID; }

    public void setName(String name) { this.name = name; }

    public void setPoints(int points) { this.points = points; }

    public void setIsScored(boolean isScore) { this.isScored = isScore; }

    public void setYear(int year) { this.year = year; }

    public void setSession(int session) { this.session = session; }

}
